# Generated by Django 5.2.9 on 2026-01-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_character_name_alter_goods_name_alter_ip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guziimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='IPKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, help_text='IP 的别名或搜索关键字，例如：星铁、崩铁、HSR', max_length=50, verbose_name='关键词')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='goods.ip', verbose_name='所属作品')),
            ],
            options={
                'verbose_name': 'IP关键词',
                'verbose_name_plural': 'IP关键词',
                'unique_together': {('ip', 'value')},
            },
        ),
    ]
