# Generated by Django 5.2.9 on 2026-01-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_category_id_alter_character_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='short_name',
        ),
    ]
