# Generated by Django 5.2.9 on 2026-01-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_populate_category_path_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '谷子', 'verbose_name_plural': '谷子'},
        ),
        migrations.AddField(
            model_name='goods',
            name='order',
            field=models.BigIntegerField(db_index=True, default=0, help_text='值越小越靠前，默认0', verbose_name='自定义排序值'),
        ),
    ]
