# Generated by Django 5.2.8 on 2026-01-23 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_alter_goods_options_goods_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='主题名称')),
                ('description', models.TextField(blank=True, help_text='主题的详细描述信息', null=True, verbose_name='主题描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='谷子所属主题，例如：夏日主题、节日主题等', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='goods.theme', verbose_name='主题'),
        ),
    ]
