# Generated by Django 5.2.8 on 2026-01-28 03:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_theme_goods_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='展柜ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='展柜名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='展柜描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='showcases/covers/', verbose_name='封面图片')),
                ('order', models.BigIntegerField(db_index=True, default=0, help_text='值越小越靠前，默认0', verbose_name='排序值')),
                ('is_public', models.BooleanField(default=True, help_text='预留字段，用于未来扩展', verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '展柜',
                'verbose_name_plural': '展柜',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseGoods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='关联ID')),
                ('order', models.BigIntegerField(db_index=True, default=0, help_text='用于在分类内排序，值越小越靠前', verbose_name='排序值')),
                ('notes', models.TextField(blank=True, help_text='在展柜中的特殊说明', null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(help_text='防止误删谷子', on_delete=django.db.models.deletion.PROTECT, related_name='showcases', to='goods.goods', verbose_name='关联谷子')),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcase_goods', to='goods.showcase', verbose_name='所属展柜')),
            ],
            options={
                'verbose_name': '展柜谷子关联',
                'verbose_name_plural': '展柜谷子关联',
                'ordering': ['order', '-created_at'],
                'unique_together': {('showcase', 'goods')},
            },
        ),
    ]
