# Generated by Django 5.2.8 on 2026-02-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_showcase_showcasecategory_showcasegoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, default='店铺：\n工艺：\n画师：\n主题：', help_text='主题的详细描述信息', null=True, verbose_name='主题描述'),
        ),
    ]
