# Generated by Django 5.2.8 on 2026-03-06 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_backfill_owner_and_enforce_user_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcasegoods',
            name='goods',
            field=models.ForeignKey(help_text='删除谷子时自动从展柜中移除', on_delete=django.db.models.deletion.CASCADE, related_name='showcases', to='goods.goods', verbose_name='关联谷子'),
        ),
    ]
