# Generated by Django 5.2.8 on 2026-04-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_alter_showcasegoods_goods_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('in_cabinet', '在馆'), ('outdoor', '出街中'), ('sold', '已售出')], default='in_cabinet', max_length=20, verbose_name='状态'),
        ),
    ]
