# Generated by Django 5.2.9 on 2026-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_storagenode_path_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagenode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
